---
title: "Endometrial Ageing: characteristics of single cell datasets"
author: "Darina Obukhova"
output: html_notebook
---
This documents describes the characteristics of endometria single cell datasets (Wang et *al.,* *Nat.Medicine*, 2020) in terms of cell types and their specific numbers. 

```{r load_libraries, include=FALSE}
library(ggplot2); library(ggsci); library(tidyverse); library(dplyr); library(gridExtra)
```

```{r load_data, include=FALSE}
C1_labels <- read.csv("/Users/darinaobukhova/projects/Endometrial_Ageing/deconvolution/data/C1/GSE111976_summary_C1_day_donor_ctype.csv")
tenx_labels <- read.csv("/Users/darinaobukhova/projects/Endometrial_Ageing/deconvolution/data/10x/GSE111976_summary_10x_day_donor_ctype.csv")
```

```{r dataset_chars, include=FALSE}
sprintf("The number of donors in C1 dataset is %i", length(unique(C1_labels$donor)))
sprintf("The number of donors in 10x dataset is %i", length(unique(tenx_labels$donor)))
sprintf("The total number of profiled cells in C1 dataset is %i", length(unique(C1_labels$cell_name)))
sprintf("The total number of profiled cells in 10x dataset is %i", length(unique(tenx_labels$cell_name)))
table(C1_labels$day, C1_labels$cell_type)
table(tenx_labels$day, tenx_labels$cell_type)
C1_labels_n <- data.frame(table(C1_labels$day, C1_labels$cell_type))
C1_labels_prop <- C1_labels_n %>% 
  pivot_wider(names_from=Var2, values_from = Freq) %>% 
  rowwise(Var1) %>% 
  mutate(total = sum(c_across(Ciliated:`Unciliated epithelia`))) %>%
  ungroup() %>% 
  mutate(across(Ciliated:`Unciliated epithelia`, ~ ./total)) 

tenx_labels_n <- data.frame(table(tenx_labels$day, tenx_labels$cell_type))
tenx_labels_prop <- tenx_labels_n %>% 
  pivot_wider(names_from=Var2, values_from = Freq) %>% 
  rowwise(Var1) %>% 
  mutate(total = sum(c_across(Ciliated:`Unciliated epithelia 2`))) %>%
  ungroup() %>% 
  mutate(across(Ciliated:`Unciliated epithelia 2`, ~ ./total))

```

```{r plot_data, include=FALSE}
C1_labels_n <- data.frame(table(C1_labels$day, C1_labels$cell_type))

C1_char = ggplot(C1_labels_n, aes(fill=Var2, y=Freq, x=Var1)) + 
  geom_col() + 
  theme_bw() +
  labs(title="C1 dataset", x="Day after onset of menstrual bleeding", y="Number of cells", fill="Cell type") +
  theme(aspect.ratio = 1,
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
C1_char_p = C1_char + scale_fill_aaas()

tenx_labels_n <- data.frame(table(tenx_labels$day, tenx_labels$cell_type))

tenx_char = ggplot(tenx_labels_n, aes(fill=Var2, y=Freq, x=Var1)) + 
  geom_col() + 
  theme_bw() + 
  labs(title="10x dataset", x="Day after onset of menstrual bleeding", y="Number of cells", fill="Cell type") +
  theme(aspect.ratio = 1,
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
tenx_char_p = tenx_char+scale_fill_aaas()
grid.arrange(C1_char_p, tenx_char_p, ncol=2)

#united_plot <- plot_grid(C1_char, tenx_char, nrow=1, labels="AUTO")

#ggsave(filename = paste0(outputdir,"singlecell_datasets_chars.pdf"), 
       #plot = united_plot, width = 25, height = 15, units = "cm")
```
